site_name: "SoME2: Interpolation"

theme:
  name: material
  palette:
    scheme: slate
    primary: pink
    accent: light blue

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
